using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.ObterCalculoCreditoImobiliario;
public class ObterCalculoCreditoImobiliarioRequest : ObterCalculoCreditoCommonRequest { }