using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.ObterCalculoCreditoEmprestimoPessoaFisica;
public class ObterCalculoCreditoEmprestimoPessoaFisicaRequest : ObterCalculoCreditoCommonRequest { }