using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.ObterCalculoCreditoConsignado;

public class ObterCalculoCreditoConsignadoRequest : ObterCalculoCreditoCommonRequest { }