using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.ValidacoesCliente.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.ValidacoesCliente.ConsultarLiberacaoCreditoCliente;
public class ConsultarLiberacaoCreditoClienteRequest : ValidacaoClienteCommonRequest { }