using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.ValidacoesCliente.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.ValidacoesCliente.ConsultarBloqueiosCliente;
public class ConsultarBloqueiosClienteRequest : ValidacaoClienteCommonRequest { }