using ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.Common;

namespace ExemploCasoContratacaoProdutoRamoFinanceiro.Application.Communication.Calculos.ObterCalculoCreditoEmprestimoPessoaJuridica;
public class ObterCalculoCreditoEmprestimoPessoaJuridicaRequest : ObterCalculoCreditoCommonRequest { }